version: '3.6'
services:
  db:
    build: db/
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

  backend_apache:
    build: backend_apache/
    restart: always
    ports:
      - "8081:80"
    environment:
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - ./backend_apache/html:/var/www/html
    depends_on:
      - db

    backend_express:
      image: node:20.11.1-alpine3.19
      restart: always
      volumes:
        - ./backend-express:/app
      working_dir: /express-api
      command: sh -c "npm install && node app.js"
      ports:
        - 3000:3000

    #進入vue-main 執行 npm run build
    frontend:
      image: nginx
      restart: always
      volumes:
        - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
        - ./frontend/vue/dist:/usr/share/nginx/html
      ports:
        - 80:80
      depends_on:
        - backend

# $time = Get-Date -Format "yyyyMMdd-HHmmss.fff"
# $hash = [System.Security.Cryptography.SHA256]::Create().ComputeHash([System.Text.Encoding]::UTF8.GetBytes($time))
# $secretKey = [System.BitConverter]::ToString($hash).Replace("-", "").ToLower()
# $env:SECRET_KEY = $secretKey
# docker-compose up
