version: '3.6'
services:
  db:
    build: db/
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
  api:
    build: api/
    restart: always
    ports:
      - "8081:80"
    environment:
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

# $time = Get-Date -Format "yyyyMMdd-HHmmss.fff"
# $hash = [System.Security.Cryptography.SHA256]::Create().ComputeHash([System.Text.Encoding]::UTF8.GetBytes($time))
# $secretKey = [System.BitConverter]::ToString($hash).Replace("-", "").ToLower()
# $env:SECRET_KEY = $secretKey
# docker-compose up